webpush: Switch on enums so that gcc knows variables are initialized
Fix these warnings:

webpush-payload.c: In function ‘webpush_payload_pad_data’:
webpush-payload.c:57:9: error: ‘result’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  return result;
         ^~~~~~

webpush-notify.c: In function ‘webpush_notify_process_msg’:
webpush-notify.c:286:6: error: ‘want_chat’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if (!webpush_notify_subscription_want(subscription, messagenew))
      ^